# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "833ad67db2ab459b4fb11f5c55b461cb"
name = "pratice-app"
handle = "pratice-app-3"
application_url = "https://tops-featuring-gourmet-assessments.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-eb545aa8.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://tops-featuring-gourmet-assessments.trycloudflare.com/auth/callback",
  "https://tops-featuring-gourmet-assessments.trycloudflare.com/auth/shopify/callback",
  "https://tops-featuring-gourmet-assessments.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
